package io.github.exo2v.vantraya.mc;

import java.util.List;
import java.util.Locale;
import java.util.TreeSet;

import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.arguments.StringArgumentType;
import com.mojang.brigadier.context.CommandContext;
import com.mojang.brigadier.exceptions.CommandSyntaxException;
import com.mojang.brigadier.suggestion.SuggestionProvider;

import io.github.exo2v.vantraya.core.BiomeLogic;
import io.github.exo2v.vantraya.core.BiomeRole;
import io.github.exo2v.vantraya.core.Spec;
import io.github.exo2v.vantraya.core.SpecVerifier;
import io.github.exo2v.vantraya.core.VantrayaModel;
import net.minecraft.ChatFormatting;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;
import net.minecraft.commands.SharedSuggestionProvider;
import net.minecraft.core.BlockPos;
import net.minecraft.core.QuartPos;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.level.biome.Climate;
import net.minecraft.world.level.chunk.ChunkGenerator;
import net.minecraft.world.level.levelgen.RandomState;
import net.neoforged.neoforge.event.RegisterCommandsEvent;

/**
 * {@code /vantraya}: look around the specification, and check the live world against it.
 *
 * <pre>
 *   /vantraya info                 the nine landmarks and the Veil of Salt
 *   /vantraya where                landmark, climate tier and fields at your feet
 *   /vantraya locate &lt;landmark&gt;    centre coordinates and elevation of a landmark
 *   /vantraya tp &lt;landmark&gt;        teleport to a landmark (operators)
 *   /vantraya verify               HANDOFF 9.4 for the running world: reads the real generator, not the model (operators)
 *   /vantraya biomes &lt;namespace&gt;   list a mod's biomes - the IDs to add to a biome role tag (operators)
 * </pre>
 */
public final class VantrayaCommand {
    private VantrayaCommand() {
    }

    private static final SuggestionProvider<CommandSourceStack> LANDMARKS = (ctx, builder) ->
            SharedSuggestionProvider.suggest(
                    Spec.LANDMARKS.stream().map(Spec.Landmark::key).toList(), builder);

    public static void onRegisterCommands(RegisterCommandsEvent event) {
        CommandDispatcher<CommandSourceStack> dispatcher = event.getDispatcher();
        dispatcher.register(Commands.literal("vantraya")
                .then(Commands.literal("info").executes(ctx -> info(ctx.getSource())))
                .then(Commands.literal("where").executes(ctx -> where(ctx.getSource())))
                .then(Commands.literal("locate")
                        .then(Commands.argument("landmark", StringArgumentType.word()).suggests(LANDMARKS)
                                .executes(ctx -> locate(ctx.getSource(), StringArgumentType.getString(ctx, "landmark")))))
                .then(Commands.literal("tp").requires(s -> s.hasPermission(2))
                        .then(Commands.argument("landmark", StringArgumentType.word()).suggests(LANDMARKS)
                                .executes(ctx -> teleport(ctx, StringArgumentType.getString(ctx, "landmark")))))
                .then(Commands.literal("verify").requires(s -> s.hasPermission(2))
                        .executes(ctx -> verify(ctx.getSource())))
                .then(Commands.literal("biomes").requires(s -> s.hasPermission(2))
                        .then(Commands.argument("namespace", StringArgumentType.word())
                                .executes(ctx -> biomes(ctx.getSource(), StringArgumentType.getString(ctx, "namespace"))))));
    }

    private static void say(CommandSourceStack src, String text) {
        src.sendSuccess(() -> Component.literal(text), false);
    }

    private static void say(CommandSourceStack src, String text, ChatFormatting colour) {
        src.sendSuccess(() -> Component.literal(text).withStyle(colour), false);
    }

    private static Spec.Landmark landmark(String key) {
        for (Spec.Landmark lm : Spec.LANDMARKS) {
            if (lm.key().equals(key)) {
                return lm;
            }
        }
        return null;
    }

    /** The Vantraya generator of the command's world, or null (and a message) when it is not a Vantraya world. */
    private static VantrayaChunkGenerator generator(CommandSourceStack src, boolean complain) {
        ChunkGenerator g = src.getLevel().getChunkSource().getGenerator();
        if (g instanceof VantrayaChunkGenerator v) {
            return v;
        }
        if (complain) {
            src.sendFailure(Component.literal("This dimension is not generated by the Vantraya world type."));
        }
        return null;
    }

    private static int info(CommandSourceStack src) {
        say(src, "Vantraya - the continent of Vantyra (Ashenfall): 8,000 x 8,000 blocks, Y -64..320, sea level Y=62",
                ChatFormatting.GOLD);
        for (int i = 0; i < Spec.LANDMARKS.size(); i++) {
            Spec.Landmark lm = Spec.LANDMARKS.get(i);
            say(src, String.format(Locale.ROOT, " %d. %s (%s) at %.0f, %.0f, %.0f  [Y %.0f-%.0f]",
                    i + 1, lm.name(), lm.key(), lm.x(), lm.y(), lm.z(), lm.yLo(), lm.yHi()));
        }
        say(src, String.format(Locale.ROOT, " rim. %s: beyond radius %.0f  [Y %.0f..%.0f]",
                Spec.VEIL.name(), Spec.VEIL_RADIUS, Spec.VEIL.yLo(), Spec.VEIL.yHi()));
        return Spec.LANDMARKS.size();
    }

    private static int where(CommandSourceStack src) {
        BlockPos pos = BlockPos.containing(src.getPosition());
        VantrayaChunkGenerator gen = generator(src, true);
        if (gen == null) {
            return 0;
        }
        VantrayaModel model = gen.model(src.getLevel().getChunkSource().randomState());
        VantrayaModel.Fields f = model.sample(pos.getX() + 0.5, pos.getZ() + 0.5);
        String place = f.landmark() >= 0 && f.landmark() < Spec.LANDMARKS.size()
                ? Spec.LANDMARKS.get(f.landmark()).name()
                : (f.landmark() == Spec.VEIL_ID ? Spec.VEIL.name() : "open land between the landmarks");
        say(src, String.format(Locale.ROOT, "%s  (x %d, z %d)", place, pos.getX(), pos.getZ()), ChatFormatting.GOLD);
        say(src, String.format(Locale.ROOT, "  surface Y %.1f   climate tier %d   temperature %.2f   humidity %.2f",
                f.height(), f.tier(), f.temperature(), f.humidity()));
        say(src, String.format(Locale.ROOT, "  continentalness %.2f   erosion %.2f   ridges %.2f",
                f.cont(), f.erosion(), f.ridges()));
        return 1;
    }

    private static int locate(CommandSourceStack src, String key) {
        Spec.Landmark lm = landmark(key);
        if (lm == null) {
            src.sendFailure(Component.literal("Unknown landmark '" + key + "'. Try /vantraya info."));
            return 0;
        }
        say(src, String.format(Locale.ROOT, "%s is centred on %.0f, %.0f (specified elevation Y=%.0f); box x %.0f..%.0f, z %.0f..%.0f",
                lm.name(), lm.x(), lm.z(), lm.y(), lm.x1(), lm.x2(), lm.z1(), lm.z2()));
        return 1;
    }

    private static int teleport(CommandContext<CommandSourceStack> ctx, String key) throws CommandSyntaxException {
        CommandSourceStack src = ctx.getSource();
        Spec.Landmark lm = landmark(key);
        if (lm == null) {
            src.sendFailure(Component.literal("Unknown landmark '" + key + "'. Try /vantraya info."));
            return 0;
        }
        VantrayaChunkGenerator gen = generator(src, true);
        if (gen == null) {
            return 0;
        }
        ServerLevel level = src.getLevel();
        VantrayaModel model = gen.model(level.getChunkSource().randomState());
        int x = (int) lm.x();
        int z = (int) lm.z();
        int y = (int) Math.ceil(Math.max(model.height(x + 0.5, z + 0.5), Spec.SEA_LEVEL)) + 3;
        ServerPlayer player = src.getPlayerOrException();
        player.teleportTo(level, x + 0.5, y, z + 0.5, player.getYRot(), player.getXRot());
        say(src, "Teleported to the " + lm.name());
        return 1;
    }

    private static int verify(CommandSourceStack src) {
        VantrayaChunkGenerator gen = generator(src, true);
        if (gen == null) {
            return 0;
        }
        ServerLevel level = src.getLevel();
        RandomState rs = level.getChunkSource().randomState();
        say(src, "Reading the live generator (terrain and biome router), not the model ...");
        SpecVerifier.Probe probe = new SpecVerifier.Probe() {
            @Override
            public int groundHeight(int x, int z) {
                return gen.terrainTopY(x, z, level, rs); // looks through cave mouths
            }

            @Override
            public BiomeRole role(int x, int y, int z) {
                Climate.TargetPoint tp = rs.sampler().sample(QuartPos.fromBlock(x), QuartPos.fromBlock(y), QuartPos.fromBlock(z));
                return BiomeLogic.classify(x, y, z,
                        Climate.unquantizeCoord(tp.temperature()), Climate.unquantizeCoord(tp.humidity()),
                        Climate.unquantizeCoord(tp.continentalness()), Climate.unquantizeCoord(tp.erosion()),
                        Climate.unquantizeCoord(tp.depth()));
            }
        };
        List<SpecVerifier.Check> checks = SpecVerifier.run(probe);
        int passed = 0;
        for (SpecVerifier.Check c : checks) {
            if (c.pass()) {
                passed++;
            }
            say(src, c.toString(), c.pass() ? ChatFormatting.GREEN : ChatFormatting.RED);
        }
        boolean ok = passed == checks.size();
        say(src, String.format(Locale.ROOT, "%d / %d checks passed - this world %s the specification.",
                passed, checks.size(), ok ? "matches" : "does NOT match"), ok ? ChatFormatting.GREEN : ChatFormatting.RED);
        return passed;
    }

    private static int biomes(CommandSourceStack src, String namespace) {
        TreeSet<String> ids = new TreeSet<>();
        for (ResourceLocation id : src.getServer().registryAccess().registryOrThrow(Registries.BIOME).keySet()) {
            if (id.getNamespace().equals(namespace)) {
                ids.add(id.toString());
            }
        }
        if (ids.isEmpty()) {
            src.sendFailure(Component.literal("No biomes in namespace '" + namespace + "'."));
            return 0;
        }
        say(src, ids.size() + " biomes in '" + namespace + "' - add the ones you want to a role tag, e.g. "
                + "data/vantraya_builder/tags/worldgen/biome/biome/temperate_forest.json:", ChatFormatting.GOLD);
        for (String id : ids) {
            say(src, "  " + id);
        }
        return ids.size();
    }
}
